### ISSUE TITLE
Discovery: Initial Runtime Solutions

### ISSUE THREAD

**Issue by ReesMcD** [The-Programming-Foundation/tutorials#4]
### Description
Research and present findings for potential "runtime" and "compilers" solutions for various languages, ie python, C/C++, unix, that the learn section will support. Preferably these solutions should be either external APIs we can leverage from the browser or libraries we can leverage. 

### Acceptance Criteria:
Present and document findings for runtime solution. 
Document what languages we can support out of the box with other libraries and what languages we will need to look into more solutions.

**Comment by yu-emily** [comment]
I know that we've been trying to find a good solution for this, so I'll also look into this issue.
