### ISSUE TITLE
Implementation: Item Carousel for Learn Home Page

### ISSUE THREAD

**Issue by ReesMcD** [The-Programming-Foundation/tutorials#6]
### Description
Implement item carousel for the learn home page as seen on the current [site](https://www.theprogrammingfoundation.org/learn). Only 3 items should be seen at one time. Confirm with UX team if want carousel animations.

#### Recommended Carousel Libraries 
[react-items-carousel](https://github.com/kareemaly/react-items-carousel)
[react-multi-carousel](https://www.npmjs.com/package/react-multi-carousel)

### Acceptance Criteria
- Learn home page item sections have an item carousel if they have more than 3 times.
- Only 3 items should be displayed on the screen at a time.
- Carousel should should be responsive.

**Comment by yu-emily** [comment]
I'm thinking about using this library for a carousel instead:
https://react-slick.neostack.com/
